name: hashing_perf
version: 0.1.0
description: Hashing performance test
environment:
  sdk: ">=1.23.0 <2.0.0"
authors:
  - Jeroen Cranendonk <jeroen.cranendonk@workiva.com>

dependencies:
  # OSS packages
  crypto: ^2.0.2+1
  uuid: ^0.5.3

dev_dependencies:
  # OSS packages
  dart_dev: ^1.7.7
  dart_style: ^1.0.6
  test: ^0.12.23

  # Private Workiva packages
  dart_medic:
    hosted:
      name: dart_medic
      url: https://pub.workiva.org
    version: ^1.3.4

transformers:
  - test/pub_serve:
      $include: test/**_test{.*,}.dart
